# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-27 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('company_stock_code', models.CharField(max_length=20)),
                ('company_logo', models.FileField(upload_to=b'')),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('demand_daily_under_proc', models.BooleanField(default=False)),
                ('demand_weekly_under_proc', models.BooleanField(default=False)),
                ('demand_monthly_under_proc', models.BooleanField(default=False)),
                ('demand_daily_entry', models.DecimalField(decimal_places=4, max_digits=100, null=True)),
                ('demand_daily_stoploss', models.DecimalField(decimal_places=4, max_digits=100, null=True)),
                ('demand_weekly_entry', models.DecimalField(decimal_places=4, max_digits=100, null=True)),
                ('demand_weekly_stoploss', models.DecimalField(decimal_places=4, max_digits=100, null=True)),
                ('demand_monthly_entry', models.DecimalField(decimal_places=4, max_digits=100, null=True)),
                ('demand_monthly_stoploss', models.DecimalField(decimal_places=4, max_digits=100, null=True)),
                ('demand_daily_lastmodified_date', models.CharField(default=b'Not Yet Run', max_length=100)),
                ('demand_weekly_lastmodified_date', models.CharField(default=b'Not Yet Run', max_length=100)),
                ('demand_monthly_lastmodified_date', models.CharField(default=b'Not Yet Run', max_length=100)),
                ('supply_daily_under_proc', models.BooleanField(default=False)),
                ('supply_weekly_under_proc', models.BooleanField(default=False)),
                ('supply_monthly_under_proc', models.BooleanField(default=False)),
                ('supply_daily_entry', models.DecimalField(decimal_places=4, max_digits=100, null=True)),
                ('supply_daily_stoploss', models.DecimalField(decimal_places=4, max_digits=100, null=True)),
                ('supply_weekly_entry', models.DecimalField(decimal_places=4, max_digits=100, null=True)),
                ('supply_weekly_stoploss', models.DecimalField(decimal_places=4, max_digits=100, null=True)),
                ('supply_monthly_entry', models.DecimalField(decimal_places=4, max_digits=100, null=True)),
                ('supply_monthly_stoploss', models.DecimalField(decimal_places=4, max_digits=100, null=True)),
                ('supply_daily_lastmodified_date', models.CharField(default=b'Not Yet Run', max_length=100)),
                ('supply_weekly_lastmodified_date', models.CharField(default=b'Not Yet Run', max_length=100)),
                ('supply_monthly_lastmodified_date', models.CharField(default=b'Not Yet Run', max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
